'use client';

import { CircleAlert } from 'lucide-react';
import { useLocale, useTranslations } from 'next-intl';
import { Label } from 'radix-ui';
import { createContext, type ReactNode, use, useId } from 'react';
import { cn } from '@/lib/cn';
import { usePlural } from '@/lib/i18n/plural';

interface FieldContextValue {
  controlId: string;
  labelId: string;
  describedBy: string | undefined;
  invalid: boolean;
  required: boolean;
  disabled: boolean;
}

const FieldContext = createContext<FieldContextValue | null>(null);

interface ControlProps {
  id?: string | undefined;
  'aria-describedby'?: string | undefined;
  'aria-invalid'?: boolean | 'true' | 'false' | 'grammar' | 'spelling' | undefined;
  'aria-required'?: boolean | 'true' | 'false' | undefined;
  disabled?: boolean | undefined;
}

/**
 * Id of the label of the enclosing Field, for a group of controls (radios) that a `<label for>`
 * cannot name: the group takes it as `aria-labelledby`.
 */
export function useFieldLabelId(): string | undefined {
  return use(FieldContext)?.labelId;
}

/**
 * Accessible attributes of the control of the enclosing Field (id of the label, description and
 * error, invalid and required states), merged with its own; the props unchanged outside a Field.
 */
export function useFieldControl<P extends ControlProps>(props: P): P {
  const field = use(FieldContext);
  if (!field) return props;
  const describedBy = [field.describedBy, props['aria-describedby']].filter(Boolean).join(' ');
  return {
    ...props,
    id: props.id ?? field.controlId,
    'aria-describedby': describedBy || undefined,
    'aria-invalid': field.invalid || props['aria-invalid'] || undefined,
    'aria-required': field.required || props['aria-required'] || undefined,
    disabled: field.disabled || props.disabled,
  };
}

interface FieldProps {
  label: ReactNode;
  /** The label stays for assistive technologies only (a search field with a visible icon). */
  hideLabel?: boolean;
  description?: ReactNode;
  /** Translated message; the field is invalid while it is set. */
  error?: string | undefined;
  /** Marked `aria-required`; the form says once that every field is required unless marked. */
  required?: boolean;
  /** Shows "optional" after the label. */
  optional?: boolean;
  disabled?: boolean;
  /**
   * Characters typed and the limit: shown under the control from 80 % of the limit, or while the
   * field has the focus; numbers in the language of the page.
   */
  counter?: { count: number; max: number };
  /** Id of the control, generated by default. */
  id?: string;
  className?: string;
  children: ReactNode;
}

/**
 * Field of a form: label, description, control, error and counter, tied together by ids
 * (`aria-describedby`, `aria-invalid`). The control reads them through useFieldControl.
 */
export function Field({
  label,
  hideLabel = false,
  description,
  error,
  required = false,
  optional = false,
  disabled = false,
  counter,
  id,
  className,
  children,
}: FieldProps) {
  const t = useTranslations('web.ui.field');
  const locale = useLocale();
  const plural = usePlural();
  const generated = useId();
  const controlId = id ?? `${generated}-control`;
  const labelId = `${generated}-label`;
  const descriptionId = description ? `${generated}-description` : undefined;
  const errorId = error ? `${generated}-error` : undefined;
  const over = counter ? counter.count > counter.max : false;
  const near = counter ? counter.count >= counter.max * 0.8 : false;
  const counterId = counter ? `${generated}-counter` : undefined;
  const number = (value: number) => new Intl.NumberFormat(locale).format(value);

  return (
    <FieldContext
      value={{
        controlId,
        labelId,
        describedBy: [descriptionId, errorId, counterId].filter(Boolean).join(' ') || undefined,
        invalid: Boolean(error) || over,
        required,
        disabled,
      }}
    >
      <div
        className={cn('group/field grid gap-1.5', className)}
        data-invalid={error || over ? '' : undefined}
      >
        <Label.Root
          id={labelId}
          htmlFor={controlId}
          className={cn(
            'text-sm font-medium text-foreground',
            hideLabel && 'sr-only',
            disabled && 'opacity-50',
          )}
        >
          {label}
          {optional ? <span className="ml-1 font-normal text-muted">{t('optional')}</span> : null}
        </Label.Root>
        {description ? (
          <p id={descriptionId} className="text-sm text-muted">
            {description}
          </p>
        ) : null}
        {children}
        {error || counter ? (
          <div className="flex items-start justify-between gap-4">
            {error ? (
              <p id={errorId} className="inline-flex items-start gap-1.5 text-sm text-danger">
                <CircleAlert aria-hidden className="mt-0.5 size-4 shrink-0" />
                {error}
              </p>
            ) : (
              <span />
            )}
            {counter ? (
              <p
                id={counterId}
                // Seen from 80 % of the limit, or while the focus is in the field.
                data-near={near ? '' : undefined}
                className={cn(
                  'shrink-0 text-xs tabular-nums',
                  over ? 'text-danger' : 'text-muted',
                  !near && 'hidden group-focus-within/field:block',
                )}
                // Announced only near the limit, not at every keystroke.
                aria-live={near ? 'polite' : 'off'}
              >
                {over
                  ? t(`counterOver.${plural(counter.count - counter.max)}`, {
                      count: number(counter.count - counter.max),
                    })
                  : t('counter', { count: number(counter.count), max: number(counter.max) })}
              </p>
            ) : null}
          </div>
        ) : null}
      </div>
    </FieldContext>
  );
}
