import { DomainError } from './domain-error';

/**
 * Minor unit exponents of the active ISO 4217 currencies (list maintained by SIX Financial
 * Information for the ISO 4217 maintenance agency). Currencies absent from the three maps below
 * have two decimals; codes absent from ACTIVE_CURRENCIES are refused.
 */
const ZERO_DECIMAL_CURRENCIES = [
  'BIF',
  'CLP',
  'DJF',
  'GNF',
  'ISK',
  'JPY',
  'KMF',
  'KRW',
  'PYG',
  'RWF',
  'UGX',
  'UYI',
  'VND',
  'VUV',
  'XAF',
  'XOF',
  'XPF',
] as const;

const THREE_DECIMAL_CURRENCIES = ['BHD', 'IQD', 'JOD', 'KWD', 'LYD', 'OMR', 'TND'] as const;

const FOUR_DECIMAL_CURRENCIES = ['CLF', 'UYW'] as const;

const TWO_DECIMAL_CURRENCIES = [
  'AED',
  'AFN',
  'ALL',
  'AMD',
  'AOA',
  'ARS',
  'AUD',
  'AWG',
  'AZN',
  'BAM',
  'BBD',
  'BDT',
  'BGN',
  'BMD',
  'BND',
  'BOB',
  'BOV',
  'BRL',
  'BSD',
  'BTN',
  'BWP',
  'BYN',
  'BZD',
  'CAD',
  'CDF',
  'CHE',
  'CHF',
  'CHW',
  'CNY',
  'COP',
  'COU',
  'CRC',
  'CUP',
  'CVE',
  'CZK',
  'DKK',
  'DOP',
  'DZD',
  'EGP',
  'ERN',
  'ETB',
  'EUR',
  'FJD',
  'FKP',
  'GBP',
  'GEL',
  'GHS',
  'GIP',
  'GMD',
  'GTQ',
  'GYD',
  'HKD',
  'HNL',
  'HTG',
  'HUF',
  'IDR',
  'ILS',
  'INR',
  'IRR',
  'JMD',
  'KES',
  'KGS',
  'KHR',
  'KPW',
  'KYD',
  'KZT',
  'LAK',
  'LBP',
  'LKR',
  'LRD',
  'LSL',
  'MAD',
  'MDL',
  'MGA',
  'MKD',
  'MMK',
  'MNT',
  'MOP',
  'MRU',
  'MUR',
  'MVR',
  'MWK',
  'MXN',
  'MXV',
  'MYR',
  'MZN',
  'NAD',
  'NGN',
  'NIO',
  'NOK',
  'NPR',
  'NZD',
  'PAB',
  'PEN',
  'PGK',
  'PHP',
  'PKR',
  'PLN',
  'QAR',
  'RON',
  'RSD',
  'RUB',
  'SAR',
  'SBD',
  'SCR',
  'SDG',
  'SEK',
  'SGD',
  'SHP',
  'SLE',
  'SOS',
  'SRD',
  'SSP',
  'STN',
  'SVC',
  'SYP',
  'SZL',
  'THB',
  'TJS',
  'TMT',
  'TOP',
  'TRY',
  'TTD',
  'TWD',
  'TZS',
  'UAH',
  'USD',
  'USN',
  'UYU',
  'UZS',
  'VES',
  'VED',
  'WST',
  'XCD',
  'XCG',
  'YER',
  'ZAR',
  'ZMW',
  'ZWG',
] as const;

const EXPONENTS: ReadonlyMap<string, number> = new Map<string, number>([
  ...ZERO_DECIMAL_CURRENCIES.map((code) => [code, 0] as const),
  ...TWO_DECIMAL_CURRENCIES.map((code) => [code, 2] as const),
  ...THREE_DECIMAL_CURRENCIES.map((code) => [code, 3] as const),
  ...FOUR_DECIMAL_CURRENCIES.map((code) => [code, 4] as const),
]);

export function isActiveCurrency(code: string): boolean {
  return EXPONENTS.has(code);
}

/** Number of decimals of the minor unit: EUR 2, XOF 0, KWD 3. */
export function currencyExponent(code: string): number {
  const exponent = EXPONENTS.get(code);
  if (exponent === undefined) {
    throw new DomainError('VALIDATION_FAILED', `Unknown ISO 4217 currency: ${code}`);
  }
  return exponent;
}

/** 10 to the power of the exponent: minor units in one major unit. */
export function minorUnitsPerMajor(code: string): bigint {
  return 10n ** BigInt(currencyExponent(code));
}
