import { v7 } from 'uuid';

/** Port: identifiers are generated by the application, never by the database. */
export abstract class IdGenerator {
  abstract next(): string;
}

export class UuidV7Generator extends IdGenerator {
  next(): string {
    return v7();
  }
}
