import {
  PROJECT_COUNTRIES_MAX,
  PROJECT_DESCRIPTION_MAX_LENGTH,
  PROJECT_DOCUMENTS_MAX,
  PROJECT_DURATION_MAX_DAYS,
  PROJECT_DURATION_MIN_DAYS,
  PROJECT_GALLERY_MAX,
  PROJECT_IMAGE_ALT_MAX_LENGTH,
  PROJECT_IMPACT_AREA_MAX_LENGTH,
  PROJECT_INTEREST_MAX_DOCUMENTS,
  PROJECT_INTEREST_MESSAGE_MAX_LENGTH,
  PROJECT_REWARD_DESCRIPTION_MAX_LENGTH,
  PROJECT_REWARD_TITLE_MAX_LENGTH,
  PROJECT_SUMMARY_MAX_LENGTH,
  PROJECT_TEAM_FUNCTION_MAX_LENGTH,
  PROJECT_TIER_DESCRIPTION_MAX_LENGTH,
  PROJECT_TIERS_MAX,
  PROJECT_TIERS_MIN,
  PROJECT_TITLE_MAX_LENGTH,
  PROJECT_UPDATE_MAX_IMAGES,
  PROJECT_UPDATE_TEXT_MAX_LENGTH,
} from '@pitchorium/contracts';
import { describe, expect, it } from 'vitest';
import { PROJECT_LIMITS } from './limits';

describe('limits of the projects', () => {
  it('equal the contracts', () => {
    expect(PROJECT_LIMITS).toEqual({
      title: PROJECT_TITLE_MAX_LENGTH,
      summary: PROJECT_SUMMARY_MAX_LENGTH,
      description: PROJECT_DESCRIPTION_MAX_LENGTH,
      impactArea: PROJECT_IMPACT_AREA_MAX_LENGTH,
      countries: PROJECT_COUNTRIES_MAX,
      gallery: PROJECT_GALLERY_MAX,
      documents: PROJECT_DOCUMENTS_MAX,
      imageAlt: PROJECT_IMAGE_ALT_MAX_LENGTH,
      tiersMin: PROJECT_TIERS_MIN,
      tiersMax: PROJECT_TIERS_MAX,
      tierDescription: PROJECT_TIER_DESCRIPTION_MAX_LENGTH,
      durationMin: PROJECT_DURATION_MIN_DAYS,
      durationMax: PROJECT_DURATION_MAX_DAYS,
      rewardTitle: PROJECT_REWARD_TITLE_MAX_LENGTH,
      rewardDescription: PROJECT_REWARD_DESCRIPTION_MAX_LENGTH,
      teamFunction: PROJECT_TEAM_FUNCTION_MAX_LENGTH,
      updateText: PROJECT_UPDATE_TEXT_MAX_LENGTH,
      updateImages: PROJECT_UPDATE_MAX_IMAGES,
      interestMessage: PROJECT_INTEREST_MESSAGE_MAX_LENGTH,
      interestDocuments: PROJECT_INTEREST_MAX_DOCUMENTS,
    });
  });
});
